// Code generated by protoc-gen-go.
// source: github.com/fuserobotics/goterram/components/physics/physics.proto
// DO NOT EDIT!

/*
Package physics is a generated protocol buffer package.

It is generated from these files:
	github.com/fuserobotics/goterram/components/physics/physics.proto

It has these top-level messages:
	PhysicsData
	PhysicsComponentInit
*/
package physics

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PhysicsData struct {
}

func (m *PhysicsData) Reset()                    { *m = PhysicsData{} }
func (m *PhysicsData) String() string            { return proto.CompactTextString(m) }
func (*PhysicsData) ProtoMessage()               {}
func (*PhysicsData) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PhysicsComponentInit struct {
	Data *PhysicsData `protobuf:"bytes,1,opt,name=data" json:"data,omitempty"`
}

func (m *PhysicsComponentInit) Reset()                    { *m = PhysicsComponentInit{} }
func (m *PhysicsComponentInit) String() string            { return proto.CompactTextString(m) }
func (*PhysicsComponentInit) ProtoMessage()               {}
func (*PhysicsComponentInit) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PhysicsComponentInit) GetData() *PhysicsData {
	if m != nil {
		return m.Data
	}
	return nil
}

func init() {
	proto.RegisterType((*PhysicsData)(nil), "physics.PhysicsData")
	proto.RegisterType((*PhysicsComponentInit)(nil), "physics.PhysicsComponentInit")
}

func init() {
	proto.RegisterFile("github.com/fuserobotics/goterram/components/physics/physics.proto", fileDescriptor0)
}

var fileDescriptor0 = []byte{
	// 138 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0x72, 0x4c, 0xcf, 0x2c, 0xc9,
	0x28, 0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0x2b, 0x2d, 0x4e, 0x2d, 0xca, 0x4f, 0xca, 0x2f,
	0xc9, 0x4c, 0x2e, 0xd6, 0x4f, 0xcf, 0x2f, 0x49, 0x2d, 0x2a, 0x4a, 0xcc, 0xd5, 0x07, 0xca, 0x14,
	0xe4, 0xe7, 0xa5, 0xe6, 0x95, 0x14, 0xeb, 0x17, 0x64, 0x54, 0x16, 0x83, 0xe4, 0xa0, 0xb4, 0x5e,
	0x41, 0x51, 0x7e, 0x49, 0xbe, 0x10, 0x3b, 0x94, 0xab, 0xc4, 0xcb, 0xc5, 0x1d, 0x00, 0x61, 0xba,
	0x24, 0x96, 0x24, 0x2a, 0x39, 0x70, 0x89, 0x40, 0xb9, 0xce, 0x30, 0x23, 0x3c, 0xf3, 0x32, 0x4b,
	0x84, 0x34, 0xb8, 0x58, 0x52, 0x80, 0xf2, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0xdc, 0x46, 0x22, 0x7a,
	0x30, 0xd3, 0x90, 0xf4, 0x06, 0x81, 0x55, 0x24, 0xb1, 0x81, 0x2d, 0x30, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x85, 0x16, 0xb5, 0x02, 0xa5, 0x00, 0x00, 0x00,
}
